/**
 * Unified event metadata schema for detection + timeline events.
 *
 * Every provider — Blink, Ring, ONVIF, etc. — should normalise its raw
 * detection data into one of these shapes so the timeline indexer and the
 * PiP doorbell-cast orchestrator can process them without provider knowledge.
 */

// ---------------------------------------------------------------------------
// Primitive value types
// ---------------------------------------------------------------------------

/** Normalised confidence score in [0, 1]. */
export type Confidence = number;

/** 2-D bounding box expressed as fractions of frame dimensions [0, 1]. */
export interface BoundingBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

// ---------------------------------------------------------------------------
// Detection classes
// ---------------------------------------------------------------------------

export type DetectionClass =
  | 'motion'
  | 'person'
  | 'face'
  | 'vehicle'
  | 'animal'
  | 'package'
  | 'doorbell'
  | 'audio_alarm'
  | 'unknown';

// ---------------------------------------------------------------------------
// Individual detection result
// ---------------------------------------------------------------------------

/** One detection observation produced by a model or rule. */
export interface DetectionResult {
  /** What was detected. */
  detectionClass: DetectionClass;
  /** Confidence score in [0, 1]. Missing means the provider didn't supply one. */
  confidence?: Confidence;
  /** Bounding box within the frame, if available. */
  boundingBox?: BoundingBox;
  /** Optional label supplied by the provider (e.g. "Known Person: Alice"). */
  label?: string;
  /** Provider-specific raw payload preserved for debugging / forward-compat. */
  raw?: unknown;
}

// ---------------------------------------------------------------------------
// Event types
// ---------------------------------------------------------------------------

export type EventType =
  | 'detection'      // triggered by an AI/rule-based detector
  | 'doorbell_press' // physical doorbell button pressed
  | 'motion_start'
  | 'motion_end'
  | 'recording_start'
  | 'recording_end'
  | 'stream_error'
  | 'stream_recovery';

// ---------------------------------------------------------------------------
// Core event envelope
// ---------------------------------------------------------------------------

/**
 * Normalised event envelope emitted by any provider or pipeline stage.
 *
 * Consumers (timeline indexer, PiP cast, Alexa, Google Home) receive this
 * type and never need to import provider-specific modules.
 */
export interface ScryptedEvent {
  /**
   * Globally unique event ID.  Generated by `createEventId()` below.
   */
  id: string;
  /** Wall-clock time the event was first observed (ms since epoch). */
  timestampMs: number;
  /** Provider identifier, e.g. "blink", "ring", "onvif". */
  provider: string;
  /** Provider-scoped device identifier. */
  deviceId: string;
  /** Human-readable device name for display purposes. */
  deviceLabel: string;
  /** Coarse event category. */
  type: EventType;
  /**
   * Detection results — non-empty for `detection` events,
   * may carry a `{ detectionClass: 'doorbell' }` entry for `doorbell_press`.
   */
  detections: DetectionResult[];
  /**
   * Average confidence across all `detections`, or `undefined` if none.
   * Computed by `computeAggregateConfidence()`.
   */
  aggregateConfidence?: Confidence;
  /**
   * Thumbnail JPEG as a base64 string for display in notifications / PiP.
   * Optional — providers supply this when available.
   */
  thumbnailBase64?: string;
  /**
   * Live-stream URL valid for the event window.
   * Populated by the Blink/Ring provider when the event starts.
   */
  liveStreamUrl?: string;
  /**
   * Duration the event is expected to be active (ms).
   * Used by the PiP cast orchestrator to know when to dismiss the overlay.
   */
  durationMs?: number;
}

// ---------------------------------------------------------------------------
// Factory helpers
// ---------------------------------------------------------------------------

let _counter = 0;

/**
 * Generate a lightweight, monotonically-increasing event ID.
 * Format: `<timestampMs>-<counter>` — good enough for in-process use.
 * Replace with UUID generation if cross-process dedup is needed.
 */
export function createEventId(timestampMs = Date.now()): string {
  return `${timestampMs}-${(++_counter).toString(36)}`;
}

/**
 * Compute the mean confidence across all detections that supply one.
 * Returns `undefined` when no detection has a confidence score.
 */
export function computeAggregateConfidence(
  detections: DetectionResult[],
): Confidence | undefined {
  const scores = detections
    .map(d => d.confidence)
    .filter((c): c is Confidence => c !== undefined);
  if (scores.length === 0) return undefined;
  return scores.reduce((s, c) => s + c, 0) / scores.length;
}

/**
 * Build a complete `ScryptedEvent` from a partial description.
 * Fills in `id`, `timestampMs`, and `aggregateConfidence` automatically.
 */
export function buildEvent(
  partial: Omit<ScryptedEvent, 'id' | 'aggregateConfidence'> &
    Partial<Pick<ScryptedEvent, 'id' | 'timestampMs' | 'aggregateConfidence'>>,
): ScryptedEvent {
  const timestampMs = partial.timestampMs ?? Date.now();
  const id = partial.id ?? createEventId(timestampMs);
  const aggregateConfidence = computeAggregateConfidence(partial.detections ?? []);
  return {
    ...partial,
    id,
    timestampMs,
    aggregateConfidence,
    detections: partial.detections ?? [],
  };
}

// ---------------------------------------------------------------------------
// Type guards
// ---------------------------------------------------------------------------

export function isDoorbellEvent(event: ScryptedEvent): boolean {
  return (
    event.type === 'doorbell_press' ||
    event.detections.some(d => d.detectionClass === 'doorbell')
  );
}

export function isMotionEvent(event: ScryptedEvent): boolean {
  return (
    event.type === 'motion_start' ||
    event.type === 'motion_end' ||
    event.detections.some(d => d.detectionClass === 'motion')
  );
}

export function isHighConfidence(
  event: ScryptedEvent,
  threshold = 0.6,
): boolean {
  return (event.aggregateConfidence ?? 0) >= threshold;
}
